### ISSUE TITLE
How to add command to a button

### ISSUE THREAD

**Issue by chros73** [nicko88/HTPCRemote#1]
Hi!

Thanks for the application!
Using v1.1 if you double click on a button (on the left of Remote editor) (`Button=1,xx,Blue`):
Unhandled exception ... : Could not find file ...\HTPCRemoteDevices.txt

Thanks

**Comment by nicko88** [comment]
Thanks for this bug report!

Not sure how I missed this in all the testing and other people who have used the program so far.

This is now fixed in Release v1.1.1

**Comment by chros73** [comment]
Thanks for the fix, works like a charm! :)
I just added a remote (e.g. Info button) for LG OLED using [aiopylgtv](https://github.com/bendavid/aiopylgtv) in a cmd (bat) file.
I'll play with your tool, adding remote for madvr in mpc-hc/be. Thanks!

Btw, can we change the color of the black / gray background of the generated html? Thanks

**Comment by nicko88** [comment]
Right now there is no way to edit the background color, but I guess I could add the option.

**Comment by nicko88** [comment]
@chros73 I added an option to customize the remote background color in v1.2 FYI.
